### PR TITLE
Pixi renderer through Graphics object is implemented

### PR DESCRIPTION
**Pull request by floatdrop**
So I used Pixi render engine to draw edges and forces in PIXI.Graphics objects (which is very close with canvas ctx in API). I'm sure, there is faster way to draw the scene, because clear graphics object in every frame refresh is very heavy operation.

My suggestion is to draw body edges in separate graphics objects once they (bodies) created and drop them to stage. But this will be different story (because we must have way to link body object with PIXI.DisplayObject to do this - may be set UID to bodies in their constructor?).

After all drawing speed is increased. I got 20 fps on 1800 particles in Canvas renderer vs 20 fps on 2800 particles in WebGl renderer.

Also I tested rendering without drawing particles on canvas, and there is results - I got drop to 20 fps on (about) 3800 particles (and got unstable fps from 30 to 50 near 3000 particles). Hope this will help you some how.

### CODE REVIEW

**Comment by floatdrop** [comment]
P.s. For example [Coffe-Physics](https://github.com/soulwire/Coffee-Physics) can do about 12000 particles without dropping fps ([see modified demo](http://floatdrop.github.io/Coffee-Physics/)).

**Comment by floatdrop** [comment]
P.p.s to be fair, if you remove walls - then newton can handle about 4000 particles on 60 fps or 6000 with 20.

**Comment by hunterloftis** [comment]
Awesome! I'll check it out shortly.

I'd like to build a non-rendering set of speed tests that can run in node to objectively measure engine changes without adding rendering to the mix. CoffeePhysics is cool, there may be things we can learn from it - however, it's a pretty limited engine that doesn't do much beyond particles, so I'm not sure how useful it will be as a relative benchmark.

**Comment by hunterloftis** [comment]
Very, very cool. Merging.

**Comment by hunterloftis** [comment]
Could you add a section to the readme about this new rendering option?

**Pull request merged**
